In [2]:
import numpy as np

In [3]:
a=[1,2,3,4]

In [4]:
np.array(a)

array([1, 2, 3, 4])

In [5]:
matrix=[[1,23,45],[13,44,65]]

In [6]:
np.array(matrix)

array([[ 1, 23, 45],
       [13, 44, 65]])

## Methodler

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
#rastgele atama 

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
#sıfır olusturuyor zeros

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
 #linspace

In [14]:
np.linspace(0,20,5) #5li aralıkta eşit aralıklı 

array([ 0.,  5., 10., 15., 20.])

In [15]:
#eye

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
#linspace arange de çok önemli

## Numpy Metodlar 2

In [20]:
#random normal dist verileri çıkartıyor bu numpy diziisi dondurur
np.random.randn(5)

array([-1.02161206,  0.6943556 ,  0.75079052, -0.81858482, -0.16920886])

In [21]:
np.random.randn(3,4)

array([[ 0.74957811, -0.16214165, -0.24690127,  0.79214667],
       [ 1.5247215 ,  0.10348164, -0.47764597,  0.46533262],
       [-0.71194836,  0.12353799,  0.04450729, -0.5636542 ]])

In [34]:
#int dondurma
np.random.randint(1,30) #son yazılan almıyor

27

In [42]:
np.random.randint(1,5,31) # iki rakam dondur bu aralıkta

array([2, 3, 1, 2, 4, 3, 4, 2, 2, 3, 2, 1, 3, 3, 3, 1, 3, 2, 3, 4, 3, 1,
       1, 1, 4, 4, 2, 4, 3, 1, 2])

In [48]:
Randmdizi=np.random.randint(1,5,20)

In [49]:
Randmdizi

array([1, 1, 4, 4, 2, 4, 4, 2, 4, 1, 2, 2, 2, 3, 4, 4, 2, 3, 2, 2])

## dizilerin kendi methodları

In [51]:
Randmdizi.reshape(5,4) #20 tane var 5x4 ayarladık biz

array([[1, 1, 4, 4],
       [2, 4, 4, 2],
       [4, 1, 2, 2],
       [2, 3, 4, 4],
       [2, 3, 2, 2]])

In [52]:
#veri setini ayarladık

In [53]:
Randmdizi.max()

4

In [54]:
Randmdizi.min()

1

In [60]:
Randmdizi.argmin() #kacıncı indexte min?

0

In [62]:
Randmdizi.shape

(20,)

In [63]:
Randmdizi

array([1, 1, 4, 4, 2, 4, 4, 2, 4, 1, 2, 2, 2, 3, 4, 4, 2, 3, 2, 2])

## Indexler

In [170]:
import numpy as np

In [171]:
dizm=np.arange(0,15)

In [172]:
dizm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [173]:
dizm[5]

5

In [174]:
dizm[3:7]

array([3, 4, 5, 6])

In [175]:
dizm[1:6]=-5

In [176]:
dizm

array([ 0, -5, -5, -5, -5, -5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [177]:
#index degerlei degisti

In [178]:
r=np.arange(0,24)

In [179]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [180]:
slicin=r[4:8]

In [181]:
slicin

array([4, 5, 6, 7])

In [182]:
slicin[:]= 700 #arrayin elemanları komple 700

In [183]:
slicin

array([700, 700, 700, 700])

In [184]:
slicin=700

In [185]:
slicin

700

In [186]:
#arraylikten int'e donstu

## matrix indexler

In [187]:
##vektorel islemlerdi bunlar

In [188]:
lst=[[12,34,56,3,23,6],[235,2,63,5,3,3],[3234234,332,4,3,6,3]]

In [189]:
mat=np.array(lst)

In [190]:
mat

array([[     12,      34,      56,       3,      23,       6],
       [    235,       2,      63,       5,       3,       3],
       [3234234,     332,       4,       3,       6,       3]])

In [191]:
mat[0][0] #iki boyutta bole yaz

12

In [192]:
#slicing

In [193]:
mat[0:2]

array([[ 12,  34,  56,   3,  23,   6],
       [235,   2,  63,   5,   3,   3]])

In [194]:
#row,column

In [195]:
mat[2:,2:]

array([[4, 3, 6, 3]])

In [196]:
yen=[[1,2,3],[5,6,432],[23,5563,78]]

In [197]:
s=np.array(yen)

In [198]:
s

array([[   1,    2,    3],
       [   5,    6,  432],
       [  23, 5563,   78]])

In [199]:
s[[0,1]]

array([[  1,   2,   3],
       [  5,   6, 432]])

In [200]:
s[[1,0]]

array([[  5,   6, 432],
       [  1,   2,   3]])

In [201]:
#fancy aslında farklı bir array olusturuyo bize

## operasyonlar

In [206]:
yenidizim=np.random.randint(1,100,20)

In [207]:
yenidizim

array([57, 54, 21, 72, 30, 91, 70, 18, 64, 12, 64, 93, 11, 60, 67, 97, 43,
       13, 25, 65])

In [208]:
#10dan buyuk rakamlar bul

In [210]:
a=yenidizim>10

In [211]:
yenidizim[a]

array([57, 54, 21, 72, 30, 91, 70, 18, 64, 12, 64, 93, 11, 60, 67, 97, 43,
       13, 25, 65])

In [212]:
#10dan buyukleri

In [213]:
t=np.arange(0,23)

In [214]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [218]:
#dizileri birbiriyle toplayaıp çıkarailiriz

In [219]:
np.sqrt(t)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576])

In [220]:
#karekok alma

In [222]:
np.max(t)

22